baseURL = 'https://notes.agostinodeangelis.com/'
languageCode = 'en-us'
title = 'Mind & Digital Era'
theme = "etch"

# Enhanced configuration for networked knowledge base
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

# Taxonomies for content organization
[taxonomies]
  tag = "tags"
  category = "categories"
  concept = "concepts"
  moc = "mocs"
  topic = "topics"
  domain = "domains"

# Content types
[contentTypes]
  [contentTypes."posts"]
    path = "posts"
    [contentTypes."posts".frontmatter]
      title = "string"
      date = "date"
      tags = "array"
      categories = "array"
      concepts = "array"
      topics = "array"
      domains = "array"
      org_roam_id = "string"
      slug = "string"
      draft = "boolean"
      backlinks = "array"
      related = "array"

# Permalinks for clean URLs
[permalinks]
  posts = "/:title/"
  mocs = "/moc/:title/"

# Menu configuration
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Articles"
    title = "Articles"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "mocs"
    name = "Knowledge Maps"
    title = "Knowledge Maps"
    url = "/mocs/"
    weight = 20

  [[menu.main]]
    identifier = "topics"
    name = "Topics"
    title = "Topics"
    url = "/topics/"
    weight = 25

  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 30

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false

# Build configuration
[build]
  writeStats = true

# Output formats
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]

# Parameters for theme customization
[params]
  description = "A networked knowledge base exploring the human mind, epistemology, and the new digital era"
  copyright = "Copyright © 2025 Mind & Digital Era"
  dark = "auto"
  highlight = true
  enableSearch = true
  enableGraph = true
  enableBacklinks = true